# Update Sefaria Links and Refine Study Routine

The user wants to update the bot to use the Sefaria Spanish translation links.

## Proposed Changes

### [Telegram Bot](file:///c:/Users/Antonio/.gemini/antigravity/scratch/telegram-study-bot/bot.py)

#### [MODIFY] [bot.py](file:///c:/Users/Antonio/.gemini/antigravity/scratch/telegram-study-bot/bot.py)
- Update `SEFARIA_TEXTOS` to `https://www-sefaria-org.translate.goog/texts?_x_tr_sl=en&_x_tr_tl=es&_x_tr_hl=es&_x_tr_pto=tc&_x_tr_hist=true`.
- Ensure other Sefaria links in the code use the translated version if applicable.
- Confirm that "Shuljan Aruj" is not present in the study blocks.

## Verification Plan

### Manual Verification
- Verify that the URLs generated by the bot correctly point to the translated Sefaria pages.
- Check the study blocks messages to ensure they match the user's requirements (Chumash Aliyah, Tehillim, Rambam, and no Shuljan Aruj).
